trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: solutionPath
    value: "**/Code/**/*.sln"

steps:
  - script: echo 'Hello students'
    displayName: 'Saying hello to the students'
  - script: ls
    displayName: 'listing all files'
  - task: DotNetCoreCLI@2
    displayName: 'Restore the code'
    inputs:
      command: 'restore'
      projects: $(solutionPath)
  - task: DotNetCoreCLI@2
    displayName: 'Build the code'
    inputs:
      command: 'build'
      projects: $(solutionPath)      
  - task: DotNetCoreCLI@2
    displayName: 'Test the code'
    inputs:
      command: 'test'
      projects: $(solutionPath)