parameters:
  - name: Environment
    type: string
  - name: WebAppName
    type: string


stages: 
  - stage: ${{ parameters.Environment }}Deployment
    jobs:
      - deployment: ${{ parameters.Environment }}
        displayName: Deploy to ${{ parameters.Environment }}
        environment: ${{ parameters.Environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo ${{ parameters.WebAppName }}
